name: Build and Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Build daemon
        run: go build -v ./cmd/daemon

      - name: Test
        run: go test -v ./...
